services:
  seednsational:
    image: cybersecnatlab/challenge-jail@sha256:d40fa9d97a4b62c68347f4b02b08ed651c39811fc8687759480699888f2f0bd6
    restart: unless-stopped
    init: true
    privileged: true
    volumes:
      - './chall:/home/user/chall:ro'
      - './glibc/ld-linux-x86-64.so.2:/home/user/ld-linux.so:ro'
      - './glibc/:/home/user/libs:ro'
    ports:
      - '7011:1337'
    environment:
      - 'SET_INTERPRETER=/home/user/ld-linux.so'
      - 'SET_RPATH=/home/user/libs'
    deploy:
      resources:
        limits:
          cpus: '0.5'
